version: '3.8'
services:
  postgresql:
    image: postgres:latest
    container_name: "postgres-compose"
    environment:
      POSTGRES_USER: fazzelis
      POSTGRES_PASSWORD: fazzelis
      POSTGRES_DB: rip
#    ports:
#      - "5432:5432"
    expose:
      5432
    networks:
      - backend-network
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "todo-backend-compose"
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    networks:
      - backend-network
    restart: on-failure:5
  nginx:
    image: nginx:latest
    container_name: "nginx-compose"
    ports:
      - "8080:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge
